### PR TITLE
增加一个新的页面?

### PR DESCRIPTION
**Pull request by nilly**
https://www.programming-idioms.org/cheatsheet/Rust

这里面 写了各种语法的demo  

请版主搬过来.

### CODE REVIEW

**Comment by pretzelhammer** [comment]
Amazing! Thank you!

**Comment by whfuyn** [comment]
What happened? w(ﾟДﾟ)w
I was still preparing this translation and asking people online to check if it contained mistakes.  Suddenly I found it merged here……
And this PR seems irrelevant to my translation: 
```
title: "Add a new page?" 
content: "[link] Here are some syntax's demos, please add it here."
```
I don't know what's going on, but I'd like to submit the PR after I finished the check.

**Comment by pretzelhammer** [comment]
@whfuyn oh, given it was a PR against my repo I had assumed it was finished, I can remove it if you'd like more time to work on it.

**Comment by whfuyn** [comment]
@pretzelhammer yes, please. I've just done the translation and it need a overall review and polish.

**Comment by pretzelhammer** [comment]
@whfuyn I've removed it, but please feel free to re-submit once it's ready! thanks.

**Pull request merged**
